apiVersion: v1
kind: Secret
metadata:
  name: voxdeploy-secrets
  namespace: voxdeploy
type: Opaque
stringData:
  GITHUB_TOKEN: "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"
  WEBHOOK_SECRET: "secret"
  GEMINI_API_KEY: "AIzaSyB1ANsRSRw2zUQ6Av3zh_sMidA17UwoYwY"
  LINGO_API_KEY: "lingo_sk_X7a_surEqVzUzu2uPDf6N1E4Ll-_hgnzgrpsQNccCzk"
