package github

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
)

func GetBranchSHA(owner, repo, branch, token string, client *http.Client) (string, error) {
	url := fmt.Sprintf("https://api.github.com/repos/%s/%s/git/refs/heads/%s", owner, repo, branch)

	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		return "", fmt.Errorf("failed to create request: %w", err)
	}

	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Accept", "application/vnd.github.v3+json")

	resp, err := client.Do(req)
	if err != nil {
		return "", fmt.Errorf("failed to get branch SHA: %w", err)
	}
	defer resp.Body.Close()

	var result struct {
		Object struct {
			SHA string `json:"sha"`
		} `json:"object"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return "", fmt.Errorf("failed to decode branch SHA: %w", err)
	}

	return result.Object.SHA, nil
}
func CreateBranch(owner, repo, newBranch, fromSHA, token string, client *http.Client) error {
	deleteURL := fmt.Sprintf("https://api.github.com/repos/%s/%s/git/refs/heads/%s", owner, repo, newBranch)
	deleteReq, _ := http.NewRequest("DELETE", deleteURL, nil)
	deleteReq.Header.Set("Authorization", "Bearer "+token)
	client.Do(deleteReq)

	url := fmt.Sprintf("https://api.github.com/repos/%s/%s/git/refs", owner, repo)
	payload := map[string]string{
		"ref": "refs/heads/" + newBranch,
		"sha": fromSHA,
	}
	body, _ := json.Marshal(payload)

	req, err := http.NewRequest("POST", url, bytes.NewBuffer(body))
	if err != nil {
		return fmt.Errorf("failed to create request: %w", err)
	}
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Content-Type", "application/json")

	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("failed to create branch: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusCreated {
		body, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("failed to create branch, status: %d, body: %s", resp.StatusCode, string(body))
	}

	return nil
}
func UpdateFile(owner, repo, branch, filePath, newContent, token string, client *http.Client) error {
	// First get the sha
	// then update and commit
	url := fmt.Sprintf("https://api.github.com/repos/%s/%s/contents/%s?ref=%s", owner, repo, filePath, branch)

	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		return fmt.Errorf("fai               led to create request: %w", err)
	}
	req.Header.Set("Authorization", "Bearer "+token)

	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("failed to get file info: %w", err)
	}
	defer resp.Body.Close()

	var fileInfo struct {
		SHA string `json:"sha"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&fileInfo); err != nil {
		return fmt.Errorf("failed to decode file info: %w", err)
	}

	// Now update the file
	updateURL := fmt.Sprintf("https://api.github.com/repos/%s/%s/contents/%s", owner, repo, filePath)

	payload := map[string]string{
		"message": "fix: AI-generated fix by VoxDeploy",
		"content": newContent, // must be base64 encoded
		"sha":     fileInfo.SHA,
		"branch":  branch,
	}
	body, _ := json.Marshal(payload)

	putReq, err := http.NewRequest("PUT", updateURL, bytes.NewBuffer(body))
	if err != nil {
		return fmt.Errorf("failed to create update request: %w", err)
	}
	putReq.Header.Set("Authorization", "Bearer "+token)
	putReq.Header.Set("Content-Type", "application/json")

	updateResp, err := client.Do(putReq)
	if err != nil {
		return fmt.Errorf("failed to update file: %w", err)
	}
	defer updateResp.Body.Close()

	if updateResp.StatusCode != http.StatusOK && updateResp.StatusCode != http.StatusCreated {
		return fmt.Errorf("failed to update file %s, status: %d", filePath, updateResp.StatusCode)
	}

	return nil
}

func CreatePullRequest(owner, repo, headBranch, baseBranch, token string, client *http.Client) (string, error) {
	url := fmt.Sprintf("https://api.github.com/repos/%s/%s/pulls", owner, repo)

	payload := map[string]string{
		"title": "VoxDeploy: AI-generated fix for failed CI",
		"body":  "This PR was automatically generated by VoxDeploy after detecting a failed GitHub Actions workflow.\n\nPlease review and merge if the fix looks correct.",
		"head":  headBranch,
		"base":  baseBranch,
	}
	body, _ := json.Marshal(payload)

	req, err := http.NewRequest("POST", url, bytes.NewBuffer(body))
	if err != nil {
		return "", fmt.Errorf("failed to create request: %w", err)
	}
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Content-Type", "application/json")

	resp, err := client.Do(req)
	if err != nil {
		return "", fmt.Errorf("failed to create PR: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusCreated {
		return "", fmt.Errorf("failed to create PR, status: %d", resp.StatusCode)
	}

	var prResp struct {
		HTMLURL string `json:"html_url"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&prResp); err != nil {
		return "", fmt.Errorf("failed to decode PR response: %w", err)
	}

	return prResp.HTMLURL, nil
}
